"""Refit the additive isotonic pricing model from new-dataset.csv.

Run:  python3 tools_fit_model.py
Writes pricing_model_data.py (generated artifact, do not hand-edit).
"""

import csv
import hashlib
import pathlib
import subprocess

import numpy as np

DATASET = pathlib.Path(__file__).with_name("new-dataset.csv")
OUTPUT = pathlib.Path(__file__).with_name("pricing_model_data.py")
TOLERANCE = 1e-9
MAX_ITERATIONS = 5000


def load_dataset():
    rows = list(csv.DictReader(DATASET.open()))
    color = np.array([float(r["color_area"]) for r in rows])
    bw = np.array([float(r["bw_area"]) for r in rows])
    price = np.array([float(r["price"]) for r in rows])
    return color, bw, color + bw, price


def pava(y, w):
    """Pool-adjacent-violators: weighted least-squares fit under y non-decreasing."""
    values, weights, counts = [], [], []
    for value, weight in zip(y, w, strict=True):
        values.append(float(value))
        weights.append(float(weight))
        counts.append(1)
        while len(values) > 1 and values[-2] > values[-1]:
            v1, v2 = values.pop(), values.pop()
            w1, w2 = weights.pop(), weights.pop()
            n1, n2 = counts.pop(), counts.pop()
            values.append((v1 * w1 + v2 * w2) / (w1 + w2))
            weights.append(w1 + w2)
            counts.append(n1 + n2)
    return np.repeat(np.array(values), counts)


def isotonic(x, y):
    """Monotone non-decreasing step fit of y on x, with clipping at the edges."""
    x = np.asarray(x, dtype=float)
    y = np.asarray(y, dtype=float)
    order = np.argsort(x, kind="stable")
    xs, ys = x[order], y[order]
    unique_x, inverse, counts = np.unique(xs, return_inverse=True, return_counts=True)
    sums = np.bincount(inverse, weights=ys)
    fitted = pava(sums / counts, counts)
    # Drop interior knots that sit flat between their neighbours: linear
    # interpolation through them is identical, so this only shrinks the artifact.
    keep = np.ones(len(fitted), dtype=bool)
    if len(fitted) > 2:
        keep[1:-1] = (fitted[1:-1] != fitted[:-2]) | (fitted[1:-1] != fitted[2:])
    return unique_x[keep], fitted[keep]


def apply_isotonic(x, knots, values):
    return np.interp(x, knots, values)


def fit_additive(print_area, color_area, price):
    """Backfit two monotone 1-D functions: mu + f_print(print) + f_color(color)."""
    mu = float(price.mean())
    f_print = np.zeros_like(price)
    f_color = np.zeros_like(price)
    knots_print = values_print = knots_color = values_color = None
    for _ in range(MAX_ITERATIONS):
        previous = f_print.copy()
        knots_print, values_print = isotonic(print_area, price - mu - f_color)
        f_print = apply_isotonic(print_area, knots_print, values_print)
        knots_color, values_color = isotonic(color_area, price - mu - f_print)
        f_color = apply_isotonic(color_area, knots_color, values_color)
        if np.abs(f_print - previous).max() < TOLERANCE:
            break
    else:
        raise RuntimeError(f"backfit did not converge in {MAX_ITERATIONS} iterations")
    return mu, knots_print, values_print, knots_color, values_color


def rounded(values):
    return tuple(round(float(v), 6) for v in values)


def main():
    color, _bw, print_area, price = load_dataset()
    mu, knots_print, values_print, knots_color, values_color = fit_additive(
        print_area, color, price
    )

    sha = hashlib.sha256(DATASET.read_bytes()).hexdigest()
    lines = [
        '"""Generated by tools_fit_model.py — do not edit by hand.',
        "",
        f"Fitted from new-dataset.csv (n={len(price)}).",
        f"Source sha256: {sha}",
        "Model: latent = INTERCEPT + f_print(print_area) + f_color(color_area),",
        "where f_print and f_color are isotonic (monotone non-decreasing) step functions.",
        '"""',
        "",
        f'DATASET_SHA256 = "{sha}"',
        f"DATASET_ROWS = {len(price)}",
        "",
        f"INTERCEPT = {mu!r}",
        "",
        f"PRINT_AREA_THRESHOLDS = {rounded(knots_print)!r}",
        "",
        f"PRINT_AREA_VALUES = {rounded(values_print)!r}",
        "",
        f"COLOR_AREA_THRESHOLDS = {rounded(knots_color)!r}",
        "",
        f"COLOR_AREA_VALUES = {rounded(values_color)!r}",
        "",
    ]
    OUTPUT.write_text("\n".join(lines))
    subprocess.run(["ruff", "format", str(OUTPUT)], check=True, capture_output=True)
    print(f"wrote {OUTPUT.name}")
    print(f"  intercept={mu:.6f}")
    print(f"  print_area: {len(knots_print)} knots")
    print(f"  color_area: {len(knots_color)} knots")


if __name__ == "__main__":
    main()
