"""Refit the additive isotonic pricing model from new-dataset.csv.

Run:  python3 tools_fit_model.py
Writes pricing_model_data.py (generated artifact, do not hand-edit).
"""

import csv
import hashlib
import pathlib
import subprocess

import numpy as np

from model_fit import fit

DATASET = pathlib.Path(__file__).with_name("new-dataset.csv")
OUTPUT = pathlib.Path(__file__).with_name("pricing_model_data.py")


def load_dataset():
    rows = list(csv.DictReader(DATASET.open()))
    color = np.array([float(r["color_area"]) for r in rows])
    bw = np.array([float(r["bw_area"]) for r in rows])
    price = np.array([float(r["price"]) for r in rows])
    return color, bw, color + bw, price


def rounded(values):
    return tuple(round(float(v), 6) for v in values)


def main():
    rows = list(csv.DictReader(DATASET.open()))
    model = fit(
        [
            {
                "bw_area": float(r["bw_area"]),
                "color_area": float(r["color_area"]),
                "price": float(r["price"]),
            }
            for r in rows
        ]
    )
    mu = model["intercept"]
    knots_print = model["print_thresholds"]
    values_print = model["print_values"]
    knots_color = model["color_thresholds"]
    values_color = model["color_values"]

    sha = hashlib.sha256(DATASET.read_bytes()).hexdigest()
    lines = [
        '"""Generated by tools_fit_model.py — do not edit by hand.',
        "",
        f"Fitted from new-dataset.csv (n={len(rows)}).",
        f"Source sha256: {sha}",
        "Model: latent = INTERCEPT + f_print(print_area) + f_color(color_area),",
        "where f_print and f_color are isotonic (monotone non-decreasing) step functions.",
        '"""',
        "",
        f'DATASET_SHA256 = "{sha}"',
        f"DATASET_ROWS = {len(rows)}",
        "",
        f"INTERCEPT = {mu!r}",
        "",
        f"PRINT_AREA_THRESHOLDS = {rounded(knots_print)!r}",
        "",
        f"PRINT_AREA_VALUES = {rounded(values_print)!r}",
        "",
        f"COLOR_AREA_THRESHOLDS = {rounded(knots_color)!r}",
        "",
        f"COLOR_AREA_VALUES = {rounded(values_color)!r}",
        "",
    ]
    OUTPUT.write_text("\n".join(lines))
    subprocess.run(["ruff", "format", str(OUTPUT)], check=True, capture_output=True)
    print(f"wrote {OUTPUT.name}")
    print(f"  intercept={mu:.6f}")
    print(f"  print_area: {len(knots_print)} knots")
    print(f"  color_area: {len(knots_color)} knots")


if __name__ == "__main__":
    main()
